In [1]:
from tools import load
import numpy as np
import re
import math
import matplotlib.pyplot as plt

In [37]:
data = np.array(load())
data = np.concatenate((data,[['']])).reshape((-1,8))
data = [[list(x.replace(".","0").replace("#","1")) for x in y[:-1]] for y in data]
data = np.array(data).astype(int)

In [ ]:
heights = []


array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1],
       [0, 1, 0, 1, 1],
       [0, 1, 0, 1, 1],
       [0, 1, 0, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [51]:
a = [x[-1].sum() == 5 for x in data] 
b = [x[0].sum() == 5 for x in data]
np.all([a[x] != b[x] for x in range(len(a))])

True

In [52]:
is_lock = b

In [59]:
data[1]

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 1, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0]])

In [58]:
sum(data[1])

array([4, 6, 5, 6, 4])

In [55]:
sum(data[0])

array([2, 6, 2, 5, 6])

In [ ]:
key_heights = []
lock_heights = []
for x in data:
    if is_lock[x]:
        lock_heights.append(sum(data[x]))
    else:
        key_heights.append(sum(data[x]))

        

[True,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True