In [16]:
from tools import load
import numpy as np
import re
import copy 

In [17]:
data = np.array(load(to_list=True, line_splitter=False)).astype(int)

In [18]:
data

array([[8, 9, 0, 1, 0, 1, 2, 3],
       [7, 8, 1, 2, 1, 8, 7, 4],
       [8, 7, 4, 3, 0, 9, 6, 5],
       [9, 6, 5, 4, 9, 8, 7, 4],
       [4, 5, 6, 7, 8, 9, 0, 3],
       [3, 2, 0, 1, 9, 0, 1, 2],
       [0, 1, 3, 2, 9, 8, 0, 1],
       [1, 0, 4, 5, 6, 7, 3, 2]])

In [19]:
trailheads = np.array(np.where(data== 0)).T

In [21]:
trailheads[0]

array([0, 2])

In [50]:
def check_trailhead(h, data):

    potential_paths = [[h]]
    
    for _ in range(10):
        new_paths = []
        for path in potential_paths: 
            required = len(path)
            last_point = path[-1]
            print(path)



                        
            if last_point[1] != (data.shape[1]-1):
                if data[last_point[0], last_point[1]+1] == required:
                    new_paths.append(path + [[last_point[0], last_point[1]+1]])
          

            if last_point[1] != 0:
                if data[last_point[0], last_point[1]-1] == required:
                    new_paths.append(path + [[last_point[0], last_point[1]-1]])


            if last_point[0] != (data.shape[0]-1):
                if data[last_point[0]+1, last_point[1]] == required:
                    new_paths.append(path + [[last_point[0]+1, last_point[1]]])


            if last_point[0] != 0:
                if data[last_point[0]-1, last_point[1]] == required:
                    new_paths.append(path + [[last_point[0]-1, last_point[1]]])

        if required == 9: 
            return new_paths
        else:
            potential_paths = copy.deepcopy(new_paths)


In [30]:
#??

In [51]:
res = []
for h in [trailheads[-3]]:
    trails = check_trailhead(list(h),data)
    end_points = len(set([str(x[-1]) for x in trails]))
    print(end_points)
    res.append(end_points)
sum(res)

[[6, 0]]
[[6, 0], [6, 1]]
[[6, 0], [6, -1]]
[[6, 0], [7, 0]]
[[6, 0], [6, 1], [5, 1]]
[[6, 0], [6, -1], [7, -1]]
[[6, 0], [6, -1], [5, -1]]
[[6, 0], [7, 0], [7, -1]]
[[6, 0], [6, 1], [5, 1], [5, 0]]
[[6, 0], [6, -1], [7, -1], [7, -2]]
[[6, 0], [6, -1], [5, -1], [5, 0]]
[[6, 0], [6, -1], [5, -1], [4, -1]]
[[6, 0], [7, 0], [7, -1], [7, -2]]
[[6, 0], [6, 1], [5, 1], [5, 0], [4, 0]]
[[6, 0], [6, -1], [5, -1], [5, 0], [4, 0]]
[[6, 0], [6, -1], [5, -1], [4, -1], [4, 0]]
[[6, 0], [6, -1], [5, -1], [4, -1], [3, -1]]
[[6, 0], [6, 1], [5, 1], [5, 0], [4, 0], [4, 1]]
[[6, 0], [6, -1], [5, -1], [5, 0], [4, 0], [4, 1]]
[[6, 0], [6, -1], [5, -1], [4, -1], [4, 0], [4, 1]]
[[6, 0], [6, -1], [5, -1], [4, -1], [3, -1], [2, -1]]
[[6, 0], [6, 1], [5, 1], [5, 0], [4, 0], [4, 1], [4, 2]]
[[6, 0], [6, 1], [5, 1], [5, 0], [4, 0], [4, 1], [3, 1]]
[[6, 0], [6, -1], [5, -1], [5, 0], [4, 0], [4, 1], [4, 2]]
[[6, 0], [6, -1], [5, -1], [5, 0], [4, 0], [4, 1], [3, 1]]
[[6, 0], [6, -1], [5, -1], [4, -1], [4, 0], [4, 

8

In [47]:
data

array([[8, 9, 0, 1, 0, 1, 2, 3],
       [7, 8, 1, 2, 1, 8, 7, 4],
       [8, 7, 4, 3, 0, 9, 6, 5],
       [9, 6, 5, 4, 9, 8, 7, 4],
       [4, 5, 6, 7, 8, 9, 0, 3],
       [3, 2, 0, 1, 9, 0, 1, 2],
       [0, 1, 3, 2, 9, 8, 0, 1],
       [1, 0, 4, 5, 6, 7, 3, 2]])

In [49]:
trails[1]

[[6, 0],
 [6, 1],
 [5, 1],
 [5, 0],
 [4, 0],
 [4, 1],
 [4, 2],
 [4, 3],
 [4, 4],
 [5, 4]]

In [42]:
trailheads[-3]

array([6, 0])

In [43]:
data

array([[8, 9, 0, 1, 0, 1, 2, 3],
       [7, 8, 1, 2, 1, 8, 7, 4],
       [8, 7, 4, 3, 0, 9, 6, 5],
       [9, 6, 5, 4, 9, 8, 7, 4],
       [4, 5, 6, 7, 8, 9, 0, 3],
       [3, 2, 0, 1, 9, 0, 1, 2],
       [0, 1, 3, 2, 9, 8, 0, 1],
       [1, 0, 4, 5, 6, 7, 3, 2]])

In [37]:
trails[0][-1]

[3, 0]

9