In [145]:
from tools import load
import numpy as np
import re
import copy

In [146]:
data = load(to_list=False, line_splitter=False)
splitter = np.where(np.array([len(x) for x in data]) == 0 )[0][0]
d1 = data[:splitter]
d1 = np.array([x.split("|") for x in d1]).astype(int)
d2 = data[splitter+1:]
d2 = [np.array(x.split(",")).astype(int) for x in d2]

In [147]:
not_allowed_behind = {}
for rule in d1:   
    if rule[1] in not_allowed_behind: 
        not_allowed_behind[rule[1]].append(rule[0])
    else: 
        not_allowed_behind[rule[1]] = [rule[0]]

In [148]:
def check_line(line, not_allowed_behind,spotting_mode=False):
    mem = []
    for i,item in enumerate(line):
        
        if item not in not_allowed_behind:
            issues = []
        else: 
            issues = [i for i in line[i+1:] if i in not_allowed_behind[item]]
            
        if spotting_mode: 
            if len(issues) > 0:
                mem.append(issues[0])
            else:
                mem.append(False) 
        else:
            if len(issues) > 0: 
                return False
    if spotting_mode: 
        return mem
    else:
        return True

In [149]:
res = []
for line in d2: 
    if check_line(line, not_allowed_behind):
        res.append(line[len(line) //2]) 
sum(res)

4872

In [150]:
def correct_single_rule(line):

    issues = check_line(line,not_allowed_behind,spotting_mode=True)
    new_line = copy.deepcopy(line)
    for n,item in enumerate(issues):
        if item: 
            swap1 = n
            swap2 = np.where(line == item)[0][0]
            memory = new_line[swap1]
            new_line[swap1] = new_line[swap2]
            new_line[swap2] = memory
            
    if check_line(new_line,not_allowed_behind):
        return True, new_line
    else:
        return False, new_line

In [151]:

#B
remain = []
for line in d2: 
    if not check_line(line, not_allowed_behind):
        remain.append(line)

In [156]:
result = []
still_remain = copy.deepcopy(remain)
while len(still_remain) != 0: 
    new_remain = []
    for line in still_remain:

        done, new = correct_single_rule(line)
        
        if done:
            result.append(new)
        else: 
            new_remain.append(new)
    still_remain = new_remain

In [157]:
res = []
for line in result: 
    res.append(line[len(line) //2]) 
sum(res)

5564

In [139]:
still_remain

[array([97, 75, 13, 47, 29])]

In [121]:
corrected

[array([97, 75, 47, 61, 53])]

In [122]:
line

array([75, 97, 47, 61, 53])

In [112]:
issues = check_line(line,not_allowed_behind,spotting_mode=True)

In [114]:
issues

[97, False, False, False, False]

In [115]:
new_line = copy.deepcopy(line)

for n,item in enumerate(issues):
    if item: 
        swap1 = n
        swap2 = np.where(line == item)[0][0]
        memory = new_line[swap1]
        new_line[swap1] = new_line[swap2]
        new_line[swap2] = memory

In [116]:
new_line

array([97, 75, 47, 61, 53])

In [117]:
line

array([75, 97, 47, 61, 53])

In [94]:
not_allowed_behind

{53: [47, 75, 61, 97],
 13: [97, 61, 29, 47, 75, 53],
 61: [97, 47, 75],
 47: [97, 75],
 29: [75, 97, 53, 61, 47],
 75: [97]}