In [150]:
# Check import:

from aocd import get_data
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import re
import numpy as np
import seaborn as sns
import matplotlib.pylab as plt

In [240]:
#data = get_data(day=2, year=2023)
#data = data.split("\n")
#data[0]

#g = 13
#b = 14
#r = 12

f = open("test.txt", "r")
f = f.read()
data = f.split("\n") 

# Nr 1 

In [162]:
d = [[y for y in list(x) if y.isnumeric()] for x in data]
sum([int(x[0] + x[-1])    for x in d])

IndexError: list index out of range

In [241]:
l = ["THISISNOTEXISTINGPROBABLY", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]

In [242]:
def edit(d):
    save = {}
    for x in l: 
        finding = d.find(x)
        if finding != -1:
            save[d.find(x)] = x
    if len(save) != 0:
        find = max(list(save.keys()))
        ind = find+len(save[find])
        d = d[:ind] + str(l.index(save[find])) + d[ind:]

    if len(save) > 1: 
        find2 = min(list(save.keys()))
        ind2 = find2+len(save[find2])
        d = d[:ind2] + str(l.index(save[find2])) + d[ind2:]
    return d

In [243]:
d = [edit(x) for x in data]

In [244]:
d = [[y for y in list(x) if y.isnumeric()] for x in d]

In [245]:
sum([int(x[0] + x[-1]) for x in d ])

53259

In [ ]:
# Some failure case??

# Nr 2

In [448]:
def check_game(l, g= 13, b=14, r=12):

    draws =l.split(":")[1].split(";")
    for draw in draws: 
        game =draw.split(",")
        #add = 0
        for game in game: 
            val = int("".join(re.findall("\d", game)))
            if ("blue" in game) and (val > b):
                    return 0
            if ("red" in game) and (val > r):
                    return 0
            if ("green" in game) and (val > g):
                    return 0
            #add += val
            #if add > g+b+r:
            #      return 0
    return int(l.split(":")[0][5:])

In [449]:
def check_game_b(l):
    b = 0 
    r = 0
    g = 0
    draws =l.split(":")[1].split(";")
    for draw in draws: 
        game =draw.split(",")
        #add = 0
        for game in game: 
            val = int("".join(re.findall("\d", game)))
            if ("blue" in game) and (val > b):
                    b = val
            if ("red" in game) and (val > r):
                    r = val
            if ("green" in game) and (val > g):
                    g = val
            #add += val
            #if add > g+b+r:
            #      return 0
    return b*r*g

In [450]:
sum([check_game(x) for x in data])

IndexError: list index out of range

In [451]:
sum([check_game_b(x) for x in data])

IndexError: list index out of range

In [ ]:
def check_game(l):


    

# Nr 3

In [455]:
data = [list(x) for x in data]

In [478]:
def check_position(pos,a=False):
    if a:
        if ((not pos.isnumeric()) and (not pos == ".")):
            return True 
        else:
            False
    else: 
        if pos == "*":
            return True 
        else:
            False


def check_adj(data, i,j, mode_a = True):
    r = len(data)
    c = len(data[0])
    return_list = []
    if i != 0: 
        if check_position(data[i-1][j]):
            return_list.append((i-1, j))

    if j != 0: 
        if check_position(data[i][j-1]):
            return_list.append((i, j-1))

    if i!= (r-1):
        if check_position(data[i+1][j]):
            return_list.append((i+1, j))

    if j != (c-1):
        if check_position(data[i][j+1]):
            return_list.append((i, j+1))
        
    # Diagonals
    if (i != 0) and (j != 0): 
        if check_position(data[i-1][j-1]):
            return_list.append((i-1, j-1))

    if (i != (r-1)) and (j != 0): 
        if check_position(data[i+1][j-1]):
            return_list.append((i+1, j-1))

    if (i != 0) and (j != (c-1)): 
        if check_position(data[i-1][j+1]):
            return_list.append((i-1, j+1))

    if (i != (r-1)) and (j != (c-1)): 
        if check_position(data[i+1][j+1]):
            return_list.append((i+1, j+1))
    if mode_a:
        if len(return_list) != 0:
            return True
        else:
            return False
    else: 
        return return_list


In [479]:
def finish_number(to_add, nr_stack, adj_stack, adj_index):
    if len(nr_stack) == 0:
        pass
    else:
        if np.any(np.array(adj_stack)):
            to_add.append((int("".join(nr_stack)), adj_index))
        else:
            #print("excluded:" + ("".join(nr_stack)))
            pass

    return to_add, [], [], []


def collect_numbers(data, adj, index = False):
    to_add = []
    nr_stack = []
    adj_stack = []
    adj_index = []
    for x in range(len(data)):
        for y in range(len(data[0])):
            if data[x][y].isnumeric():
                nr_stack.append(data[x][y])
                adj_stack.append(adj[x][y])
                adj_index.append(index[x][y])

                if y == (len(data[0]) - 1):
                    to_add, nr_stack, adj_stack, adj_index = finish_number(
                        to_add, nr_stack, adj_stack, adj_index
                    )
                else:
                    if data[x][y + 1].isnumeric():
                        pass
                    else:
                        to_add, nr_stack, adj_stack, adj_index = finish_number(
                            to_add, nr_stack, adj_stack, adj_index
                        )

    return to_add

In [480]:
adj = [[[check_adj(data,x,y)] for y in range(len(data[0]))] for x in range(len(data))]
adj_index = [[check_adj(data,x,y, mode_a=False) for y in range(len(data[0]))] for x in range(len(data))]

In [481]:
# All numbers only have max one adjacent gear. good.
# stack = []
# for n,x in enumerate(adj_index): 
#     for m, y in enumerate(x):
#         stack.append(len(y))
#         if len(y) == 2: 
#             print(data[n][m])

In [482]:
res = collect_numbers(data, adj, adj_index)

In [483]:
res

[(35, [[(1, 101)], []]),
 (863, [[(2, 8)], [(2, 8)], [(2, 8)]]),
 (36, [[(2, 34)], []]),
 (956, [[(2, 49)], [], []]),
 (692, [[(2, 64)], [], []]),
 (744, [[(1, 82)], [], []]),
 (475, [[(3, 13)], [], []]),
 (996, [[], [], [(2, 34)]]),
 (395, [[], [], [(3, 46)]]),
 (453, [[(1, 101)], [(1, 101)], []]),
 (535, [[(3, 106)], [(3, 106)], []]),
 (470, [[(2, 8)], [], []]),
 (40, [[], [(2, 64)]]),
 (649, [[], [], [(4, 127)]]),
 (587, [[(3, 13)], [(3, 13)], []]),
 (848, [[], [], [(4, 40)]]),
 (415, [[], [(5, 100)], [(5, 100)]]),
 (445, [[(3, 106)], [(3, 106)], [(3, 106)]]),
 (79, [[], [(5, 30)]]),
 (660, [[(5, 30)], [], []]),
 (87, [[(4, 40)], []]),
 (926, [[(4, 127)], [(4, 127)], [(4, 127)]]),
 (846, [[(7, 34)], [], []]),
 (870, [[], [], [(6, 62)]]),
 (874, [[(6, 62)], [], []]),
 (610, [[(7, 67)], [], []]),
 (825, [[(5, 100)], [], []]),
 (689, [[(7, 118)], [(7, 118)], []]),
 (700, [[(8, 23)], [(8, 23)], [(8, 23)]]),
 (693, [[(8, 115)], [(8, 115)], [(8, 115)]]),
 (59, [[(8, 135)], [(8, 135)]]),
 

In [484]:
def reduce_index(l):
    out = []
    for x in l[1]:
        if len(x) == 0: 
            pass
        else:
            for y in x: 
                out.append(y)
    return set(out)

In [485]:
res_2 = []
for x in range(len(res)):
    res_2.append([res[x][0],reduce_index(res[x])])

In [486]:
# check
max([len(x[1]) for x in res_2])


1

In [487]:
stack_final = []
for n,x in enumerate(res_2):
    stack = []
    for m, y in enumerate(res_2):
        if x[1] == y[1] and (n!=m):
            stack.append((x[0],y[0]))
    stack_final.append(stack)

In [488]:
# good
max([len(x) for x in stack_final])

1

In [466]:
sum([x[0][0] * x[0][1] for x in stack_final if (len(x) != 0)]) /2


59755577.0

In [489]:
sum([x[0][0] * x[0][1] for x in stack_final if (len(x) != 0)]) /2


72246648.0

# Nr 4

In [619]:
def parse(l):
    return [
        int(x) for x in l.split(": ")[1].split(" | ")[0].replace("  ", " ").split(" ") if len(x) > 0
    ], [int(x) for x in l.split(": ")[1].split(" | ")[1].replace("  ", " ").split(" ") if len(x) > 0 ]


def calc_val(l, return_matches= False):
    matches = len(l[0]  + l[1]) - len(set(l[0]  + l[1]))
    if return_matches: 
        return matches
    if matches == 1: 
        return 1
    elif matches == 0: 
        return 0
    else:
        return 1*2**(len(l[0]  + l[1]) - len(set(l[0]  + l[1])) -1)

In [620]:
data = [parse(l) for l in data]

In [621]:
#a
sum([calc_val(x) for x in data])

23235

In [622]:
out = []
count = {x: 1 for x in range(len(data))}
for n,x in enumerate(data):
    val = calc_val(x, return_matches=True)
    score =  calc_val(x)
    for match in range(1,val+1):
        count[n+match] += (1*count[n])

In [623]:
sum([count[x] for x in count.keys()])

5920640

# Nr 5

In [129]:
seeds = [int(x) for x in data[0].split(": ")[1].split(" ")]

In [130]:
def process_seeds(seeds):
    stack = []
    s = np.array(seeds).reshape(-1,2)
    s[:,1] = s[:,0] + s[:,1]
    stack.append(s)
    return stack[0]

In [131]:
seeds = process_seeds(seeds)

In [132]:
hold = {}
name_stack = []
for x in data[2:]: 
    if  "-" in x:
        stack = []
        name = x[:-1]
    elif (x == "") or x == data[-1]:
        hold[name] = np.array(stack)
        name_stack.append(name)
    else:
        stack.append([int(y) for y in x.split(" ")])

In [145]:
def calc_new_ranges(in_range, mapping):
    out = []
    rang = in_range
    for x in mapping: 
        if x[1] > rang[1] or ((x[1]+x[2]) < rang[0]):
             # nonoverlapping
             pass
        elif (x[1] < rang[0]) and (x[1]+ x[2]-1) >= rang[1]:
            # fully emerged
            out.append([x[0] + rang[0] - x[1], x[0] + rang[1] - x[1]])
            in_range = [0,0]

        elif x[1] < rang[0]:
            
            # bottom < rang
            pass


        elif (x[1]+ x[2]-1) >= rang[1]:
            # top > rang
            pass

        else:
            pass

    if (rang[0] - rang[1])  == 0: 
        pass
    else: 
        out.append(rang)

    return rang
    

In [151]:
new_seeds = seeds
for x in name_stack:
    for y in new_seeds:
        calc_new_ranges(y, hold[x])

RecursionError: maximum recursion depth exceeded in comparison

In [150]:
hold

{'seed-to-soil map': array([[50, 98,  2],
        [52, 50, 48]]),
 'soil-to-fertilizer map': array([[ 0, 15, 37],
        [37, 52,  2],
        [39,  0, 15]]),
 'fertilizer-to-water map': array([[49, 53,  8],
        [ 0, 11, 42],
        [42,  0,  7],
        [57,  7,  4]]),
 'water-to-light map': array([[88, 18,  7],
        [18, 25, 70]]),
 'light-to-temperature map': array([[45, 77, 23],
        [81, 45, 19],
        [68, 64, 13]]),
 'temperature-to-humidity map': array([[ 0, 69,  1],
        [ 1,  0, 69]]),
 'humidity-to-location map': array([[60, 56, 37]])}

In [140]:
hold['seed-to-soil map']

array([[50, 98,  2],
       [52, 50, 48]])

In [756]:
# ah hell na.
#seedsn = process_seeds(seeds)
#len(seedsn)

In [75]:
seeds

[2276375722,
 160148132,
 3424292843,
 82110297,
 1692203766,
 342813967,
 3289792522,
 103516087,
 2590548294,
 590357761,
 1365412380,
 80084180,
 3574751516,
 584781136,
 4207087048,
 36194356,
 1515742281,
 174009980,
 6434225,
 291842774]

In [748]:
def move_forward(seed, mapping):
    for x in mapping: 
        if (seed >= x[1]) and((x[1]+ x[2]) >= seed ):
            return x[0] + (seed -x[1])
    return seed

In [749]:
#a 
new_seed = seedsn
for mapp in name_stack:
    new_seed =   [move_forward(x, hold[mapp]) for x in new_seed] 
min(new_seed)

In [71]:
def check_pass_through(ranges, out_range):
    for line in ranges.values[1:]: 
        if line[0] > out_range[1]:
            pass
        else:
            print("line check!")
        

        

In [ ]:
#b 

ranges = pd.DataFrame(hold['humidity-to-location map'])
ranges[3] = ranges[0] + ranges[2]-1
ranges[4] = ranges[1] + ranges[2]-1
ranges = ranges.sort_values(3)

top_range = [ranges.iloc[:1].values[0,1],ranges.iloc[:1].values[0,4]]
out_range = [ranges.iloc[:1].values[0,0],ranges.iloc[:1].values[0,3]]

In [73]:
ranges

0           1          2           3           4
13           0  3024237462  156854744   156854743  3181092205
15   156854744  3181092206  437120116   593974859  3618212321
18   593974860  2074095641  171967880   765942739  2246063520
9    765942740           0  407047779  1172990518   407047778
16  1172990519   472694271  459890829  1632881347   932585099
2   1632881348   407047779   65646492  1698527839   472694270
12  1698527840  1407025045   34229631  1732757470  1441254675
7   2192942437  1028113266  378911779  2571854215  1407025044
6   2571854216  2932834724   91402738  2663256953  3024237461
10  2663256954  1441254676   66616909  2729873862  1507871584
4   2729873863  4028012661   26534599  2756408461  4054547259
11  2756408462  4054547260   93435122  2849843583  4147982381
0   2849843584  4147982382   56632112  2906475695  4204614493
17  2906475696  3973741766   54270895  2960746590  4028012660
8   2960746591   932585100   95528166  3056274756  1028113265
3   3056274757  2246063521  686771203  3743045959  2932834723
14  3743045960  1507871585   36024955  3779070914  1543896539
5   3779070915  1543896540   70014135  3849085049  1613910674
1   3849085050  3618212322  355529444  4204614493  3973741765

In [69]:
#b 

ranges = pd.DataFrame(hold['humidity-to-location map'])
ranges[3] = ranges[0] + ranges[2]-1
ranges[4] = ranges[1] + ranges[2]-1
ranges = ranges.sort_values(3)

top_range = [ranges.iloc[:1].values[0,1],ranges.iloc[:1].values[0,4]]
out_range = [ranges.iloc[:1].values[0,0],ranges.iloc[:1].values[0,3]]


check_pass_through(ranges)

In [68]:
top_range

[3024237462, 3181092205]

In [65]:
stack = []
for x in hold['temperature-to-humidity map']:

    if x[1] > top_range[1]:
        pass
    elif (x[1] + x[2]) < top_range[0]:
        pass 
    else:
        stack.append(x)
stack = np.array(stack)

In [66]:
stack

array([[1119061522, 3123774174,  108864966],
       [1727156113, 3113814046,    9960128],
       [ 407962871, 2998327877,   37336959],
       [1406753618, 3035664836,   78149210]])

In [62]:
hold['temperature-to-humidity map']

array([[1008510114, 1939290935,   27755995],
       [2205283444, 4197517502,   16218189],
       [1119061522, 3123774174,  108864966],
       [1566495924,  221087407,   33939034],
       [3089618547, 3728555042,   25452278],
       [2341294643, 3455988869,   16076350],
       [2286651827, 3754007320,   54642816],
       [ 704748216, 2542375745,   76754089],
       [ 445299830, 3938069116,  259448386],
       [1036266109, 1300576315,   82795413],
       [ 178337856, 1565003866,   40230920],
       [2122934367, 1605234786,   81339593],
       [1484902828,  980285858,   81593096],
       [2823460240, 1967046930,  266158307],
       [3827446421, 1526750766,   38253100],
       [ 984919715, 1161567987,   23590399],
       [ 218568776, 1061878954,   99689033],
       [4049237602, 3232639140,  223349729],
       [ 953670836, 2233205237,    3881060],
       [ 318257809, 3472065219,   89705062],
       [1727156113, 3113814046,    9960128],
       [3733360236,  444372828,   94086185],
       [42

In [47]:
top_range

[3024237462, 3181092205]

In [40]:
ranges.sort_values(3).iloc[:1][0][4]

KeyError: 4

In [25]:
ranges.sort_values(3)

0           1          2           3           4
13           0  3024237462  156854744   156854743  3181092205
15   156854744  3181092206  437120116   593974859  3618212321
18   593974860  2074095641  171967880   765942739  2246063520
9    765942740           0  407047779  1172990518   407047778
16  1172990519   472694271  459890829  1632881347   932585099
2   1632881348   407047779   65646492  1698527839   472694270
12  1698527840  1407025045   34229631  1732757470  1441254675
7   2192942437  1028113266  378911779  2571854215  1407025044
6   2571854216  2932834724   91402738  2663256953  3024237461
10  2663256954  1441254676   66616909  2729873862  1507871584
4   2729873863  4028012661   26534599  2756408461  4054547259
11  2756408462  4054547260   93435122  2849843583  4147982381
0   2849843584  4147982382   56632112  2906475695  4204614493
17  2906475696  3973741766   54270895  2960746590  4028012660
8   2960746591   932585100   95528166  3056274756  1028113265
3   3056274757  2246063521  686771203  3743045959  2932834723
14  3743045960  1507871585   36024955  3779070914  1543896539
5   3779070915  1543896540   70014135  3849085049  1613910674
1   3849085050  3618212322  355529444  4204614493  3973741765

In [723]:
hold['fertilizer-to-water map']

array([[49, 53,  8],
       [ 0, 11, 42],
       [42,  0,  7],
       [57,  7,  4]])

In [724]:
move_forward(53, hold['fertilizer-to-water map'])

53

# Nr 6

In [197]:
games  = np.array([[int(x) for x in data[y][11:].split(" ") if x != ""] for y in [0,1]]).T

In [213]:
gamesb  = np.array([int("".join(data[0][11:].split(" "))),  int("".join(data[1][11:].split(" ")))])

In [194]:
stack = []
for x in games:
    a = np.arange(1,x[0])
    b = np.flip(a)
    stack.append(sum((a * b) >x[1]))

In [214]:
a = np.arange(1,gamesb[0])
b = np.flip(a)
sum((a * b) >gamesb[1])

46561107

# Nr 7

In [174]:
import operator

In [175]:
def parse(d, joker_rule=False):
    data = [x.split(" ") for x in d]
    for x in range(len(data)): 
        data[x][0] = list(data[x][0])
        data[x][1] = int(data[x][1])
        for y in range(len(data[x][0])):
            if data[x][0][y] == "T":
                data[x][0][y] = 10
            if data[x][0][y] == "J":
                if joker_rule:
                    data[x][0][y] = -1
                else:
                    data[x][0][y] = 11
            if data[x][0][y] == "Q":
                data[x][0][y] = 12
            if data[x][0][y] == "K":
                data[x][0][y] = 13
            if data[x][0][y] == "A":
                data[x][0][y] = 14
            else:
                data[x][0][y] = int(data[x][0][y])
        data[x][0] = data[x][0]
    return data

In [179]:
def check_hand_value(h, joker_rule=False):

    if joker_rule: 
        a,b = np.unique([x for x in h if x != -1], return_counts=True)
        if len(b) == 0: 
            return 7 # 5 jokers
        best = a[b.argmax()]
        h = [x if (x != -1) else best for x in h]

    l = len(set(h))

    if l == 1:
        return 7 
    if l == 2:
        if np.unique(h, return_counts=True)[1].max() == 4:
            return 6
        else:
            return 5
    if l ==3: 
        if np.unique(h, return_counts=True)[1].max() == 3:
            return 4
        else:
            return 3    
    if l == 4: 
        return 2
    else: 
        return 1

In [180]:
def compare(d, joker_rule=False):
    ordering = []
    for x in d:
        ordering.append([check_hand_value(x[0], joker_rule=joker_rule)] + x[0] + [x[1]])
    sorted_list = sorted(ordering, key=operator.itemgetter(0, 1,2,3,4,5))
    return (np.array(sorted_list)[:,-1] * np.arange(1,len(sorted_list)+1)).sum()

In [181]:
d = parse(data, joker_rule=True)
compare(d, joker_rule=True)

251195607